const profile = {
  name: "최보민",
  email: "bomin1995@naver.com",
  tel: "010-5069-9108",
};

export { profile };

const portfolio = [
  {
    id: 1,
    title: "1.디지털서비스개방",
    type: "Jquery Responsive Web",
    font: ["Noto Sans Korean"],
    info: "실무 업무로 Jquery를 이용하여 제작한 반응형 디지털 플랫폼 정부 사업 홈페이지입니다.",
    color: [""],
    colorh: [""],
    skill: ["React", "React-router-dom", "Axios"],
    prom: [],
    srcr: process.env.PUBLIC_URL + "/assets/img/work01_01.png",
    src: process.env.PUBLIC_URL + "/assets/img/work01_02.png",
    link: "https://qha1995.github.io/Openapi_Usermain/public/html/00%EB%A9%94%EC%9D%B8.html ",
  },
  {
    id: 2,
    title: "2.대한적십자사",
    type: "Jquery Responsive Web",
    font: ["Noto Sans Korean"],
    info: "실무 업무로 Jquery를 이용하여 제작한 반응형 대한적십자사 메인 홈페이지입니다.",
    colorh: [""],
    color: [""],
    skill: ["React", "React-router-dom", "Axios"],
    promh: ["WORK "],
    promt: ["실무 업무로 작업한 대한적십자사 프로모션 싱글 페이지입니다."],
    prom: [
      {
        nme: "page 1",
        lnk: "https://qha1995.github.io/2022greenwood_fundraise/public/html/index.html",
      },
      {
        nme: "page 2",
        lnk: "https://qha1995.github.io/RCY70_memorialpage/public/html/index.html",
      },
      {
        nme: "page 3",
        lnk: "https://qha1995.github.io/turkey_relief/index.html",
      },
      {
        nme: "page 4",
        lnk: "https://qha1995.github.io/ukraine_campaign/public/%EC%9A%B0%ED%81%AC%EB%9D%BC%EC%9D%B4%EB%82%98%EC%BA%A0%ED%8E%98%EC%9D%B8.html",
      },
    ],
    srcr: process.env.PUBLIC_URL + "/assets/img/work02_01.png",
    src: process.env.PUBLIC_URL + "/assets/img/work02_02.png",
    link: "https://qha1995.github.io/redcross_main/public/html/main.html",
    plink: [],
  },
  {
    id: 3,
    title: "3.도서대여사이트",
    type: "React Axios 1920 Web",
    font: ["Noto Sans Korean"],
    info: "인턴 과제로 React와 Axios를 이용하여 1920 사이즈에 맞춰 디자인한 도서 대여 사이트입니다.",
    color: [" "],
    colorh: [""],
    skill: ["React", "React-router-dom", "Axios"],
    prom: [],
    srcr: process.env.PUBLIC_URL + "/assets/img/work03_02.png",
    src: process.env.PUBLIC_URL + "/assets/img/work03_02.png",
    link: "https://qha1995.github.io/book_rental",
  },
  {
    id: 4,
    title: "4.NYX",
    type: "React Axios Responsive Web",
    font: ["Noto Sans Korean"],
    info: "React와 Axios로 리디자인한 반응형 NYX 홈페이지입니다.",
    color: ["#000"],
    colorh: ["COLOR"],
    skill: ["React", "React-router-dom", "Axios"],
    prom: [],
    srcr: process.env.PUBLIC_URL + "/assets/img/portfolio05_1.png",
    src: process.env.PUBLIC_URL + "/assets/img/portfolio05_2.png",
    link: "https://qha1995.github.io/choibomin_NYX",
  },

  {
    id: 5,
    title: "5.에버랜드",
    type: "React Responsive Web",
    font: ["Noto Sans Korean"],
    info: "React로 리디자인한 반응형 에버랜드 홈페이지입니다.",
    color: ["#f5a100"],
    colorh: ["COLOR"],
    skill: ["React", "React-router-dom"],
    prom: [],
    srcr: process.env.PUBLIC_URL + "/assets/img/portfolio01_1.png",
    src: process.env.PUBLIC_URL + "/assets/img/portfolio01_2.png",
    link: "https://qha1995.github.io/portfolio_everland/",
  },
  {
    id: 6,
    title: "6.고요의바다",
    type: "Fullpage Responsive Web",
    font: ["Noto Sans Korean"],
    info: "Fullpage로 디자인한 반응형 홈페이지입니다.",
    color: ["#000"],
    colorh: ["COLOR"],
    skill: ["Fullpage"],
    prom: [],
    srcr: process.env.PUBLIC_URL + "/assets/img/portfolio02_1.png",
    src: process.env.PUBLIC_URL + "/assets/img/portfolio02_2.png",
    link: "https://qha1995.github.io/choibomin_silence/",
  },
  {
    id: 7,
    title: "7.대한항공",
    type: "Jquery Responsive Web",
    font: ["Noto Sans Korean"],
    info: "Jquery로 리디자인한 반응형 대한항공 홈페이지입니다. ",
    color: ["#00256c"],
    colorh: ["COLOR"],
    skill: ["Jquery"],
    prom: [],
    srcr: process.env.PUBLIC_URL + "/assets/img/portfolio03_1.png",
    src: process.env.PUBLIC_URL + "/assets/img/portfolio03_2.png",
    link: "https://qha1995.github.io/choibomin_koreanair/",
  },
  {
    id: 8,
    title: "8.Nonfiction",
    type: "Jquery Responsive Web",
    font: ["Noto Sans Korean"],
    info: "Jquery로 리디자인한 반응형 Nonfiction 홈페이지입니다.",
    color: ["#000"],
    colorh: ["COLOR"],
    skill: ["Jquery"],
    prom: [],
    srcr: process.env.PUBLIC_URL + "/assets/img/portfolio04_1.png",
    src: process.env.PUBLIC_URL + "/assets/img/portfolio04_2.png",
    link: "https://qha1995.github.io/choibomin_nonfiction/",
  },

  {
    id: 9,
    title: "9.training",
    training: [
      {
        id: 1,
        title: "1.현대엘리베이트",
        type: "React, Javascript, Jquery Responsive Web",
        font: ["Noto Sans Korean"],
        info: "React, Javascript, Jquery로 실습한 페이지입니다.",
        color: ["#333"],
        colorh: ["COLOR"],
        skill: [
          { nme: "React", lnk: "https://qha1995.github.io/hd_web_react" },
          {
            nme: "Javascript",
            lnk: "https://qha1995.github.io/hd_web_javascript/",
          },
          { nme: "Jquery", lnk: "https://qha1995.github.io/hd_web/" },
        ],
        src: process.env.PUBLIC_URL + "/assets/img/trn_01.png",
        link: [
          "https://qha1995.github.io/hd_web_react",
          "https://qha1995.github.io/hd_web_javascript/",
          "https://qha1995.github.io/hd_web/",
        ],
      },
      {
        id: 2,
        title: "2.NETFLIX",
        type: "React Axios Responsive Web",
        font: ["Noto Sans Korean"],
        info: "React와 Axios로 실습한 페이지입니다.",
        color: ["#333"],
        skill: [
          { nme: "React", lnk: "https://qha1995.github.io/Axios_practice01" },
        ],
        src: process.env.PUBLIC_URL + "/assets/img/trn_02.png",
      },
      {
        id: 3,
        title: "3.동진쎄미캠",
        type: "Gnuboard",
        font: ["Noto Sans Korean"],
        info: "Gnuboard를 실습한 페이지입니다. ",
        color: ["#333"],
        skill: [{ nme: "Gnuboard", lnk: "http://bomin1995.dothome.co.kr/" }],
        srcr: process.env.PUBLIC_URL + "/assets/img/portfolio03_1.png",
        src: process.env.PUBLIC_URL + "/assets/img/trn_03.png",
      },
    ],
  },
];

export { portfolio };
